ALTER TABLE user_stats
    ADD COLUMN IF NOT EXISTS total_days_active INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_chat_sessions INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_active_date BIGINT,
    ADD COLUMN IF NOT EXISTS streak_start_date BIGINT,
    ADD COLUMN IF NOT EXISTS average_mood_score DOUBLE PRECISION;
